---
- name: Stop service on Linux
  service:
    name: "{{ service_name }}"
    state: stopped
  become: true

- name: Start service on Linux
  service:
    name: "{{ service_name }}"
    state: started
  become: true
