---
- name: Stop service on Windows
  win_service:
    name: "{{ service_name }}"
    state: stopped

- name: Start service on Windows
  win_service:
    name: "{{ service_name }}"
    state: started
